services:
  db:
    image: postgres:16-alpine
    container_name: aepapa_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-aepapa}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - aepapa-network

  redis:
    image: redis:6-alpine
    container_name: aepapa_redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - aepapa-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: aepapa_rabbitmq
    restart: always
    networks:
      - aepapa-network

networks:
  aepapa-network:
    external: true

volumes:
  db-data:
  redis-data:
