name: Deploy Backend AEPAPA

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Atualizar Servidor Oracle
    runs-on: ubuntu-latest

    steps:
      - name: Executar comandos via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 35m  
          script: |
            cd ~/aepapa
            
            git fetch origin master
            git reset --hard origin/master            
            
            docker compose -f docker-compose.prod.yml build --pull app
            
            docker compose -f docker-compose.prod.yml up -d --force-recreate app worker nginx
            
            sudo chmod -R 777 ~/aepapa/src
            docker compose -f docker-compose.prod.yml exec -T app composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader
            docker compose -f docker-compose.prod.yml exec -T app chown -R www-data:www-data /var/www
            
            docker compose -f docker-compose.prod.yml restart worker
            
            docker image prune -f
            docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force
            docker compose -f docker-compose.prod.yml exec -T app php artisan optimize:clear
            docker compose -f docker-compose.prod.yml exec -T app php artisan optimize
